"""initial_schema

Revision ID: 190ba874409c
Revises: 
Create Date: 2026-09-30 21:16:46.375462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '190ba874409c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species_reference',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('taxon_name', sa.String(length=255), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('order_name', sa.String(length=255), nullable=True),
    sa.Column('family_name', sa.String(length=255), nullable=True),
    sa.Column('bmwp_score', sa.Integer(), nullable=False),
    sa.Column('water_quality_indication', sa.String(length=50), nullable=False),
    sa.Column('is_disease_vector', sa.Boolean(), nullable=False),
    sa.Column('ecological_description', sa.Text(), nullable=False),
    sa.Column('educational_text', sa.Text(), nullable=False),
    sa.Column('one_health_significance', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('fun_fact', sa.String(length=500), nullable=True),
    sa.Column('habitat', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxon_name')
    )
    op.create_index('idx_species_taxon', 'species_reference', ['taxon_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('VOLUNTEER', 'RESEARCHER', name='user_role'), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('image_thumbnail_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('pilot_city', sa.String(length=100), nullable=True),
    sa.Column('observed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'AUTO_VALIDATED', 'PENDING_REVIEW', 'EXPERT_VALIDATED', 'REJECTED', name='observation_status'), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('routing', sa.String(length=50), nullable=True),
    sa.Column('top_species', sa.String(length=255), nullable=True),
    sa.Column('top_confidence', sa.Float(), nullable=True),
    sa.Column('impact_text', sa.Text(), nullable=True),
    sa.Column('impact_headline', sa.String(length=255), nullable=True),
    sa.Column('pipeline_time_seconds', sa.Float(), nullable=True),
    sa.Column('pipeline_error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_observations_confidence', 'observations', ['confidence_score'], unique=False)
    op.create_index('idx_observations_created_at', 'observations', ['created_at'], unique=False)
    op.create_index('idx_observations_pilot_city', 'observations', ['pilot_city'], unique=False)
    op.create_index('idx_observations_review_queue', 'observations', ['status', 'created_at'], unique=False)
    op.create_index('idx_observations_status', 'observations', ['status'], unique=False)
    op.create_index('idx_observations_status_created', 'observations', ['status', 'created_at'], unique=False)
    op.create_index('idx_observations_top_species', 'observations', ['top_species'], unique=False)
    op.create_index('idx_observations_user_history', 'observations', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_observations_user_id', 'observations', ['user_id'], unique=False)
    op.create_table('ai_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_count_input', sa.Integer(), nullable=True),
    sa.Column('token_count_output', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_results_agent', 'ai_results', ['agent_name'], unique=False)
    op.create_index('idx_ai_results_obs_agent', 'ai_results', ['observation_id', 'agent_name'], unique=True)
    op.create_index('idx_ai_results_observation', 'ai_results', ['observation_id'], unique=False)
    op.create_table('expert_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CONFIRM', 'CORRECT', 'REJECT', name='review_action'), nullable=False),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('review_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    op.create_index('idx_reviews_observation', 'expert_reviews', ['observation_id'], unique=False)
    op.create_index('idx_reviews_reviewer', 'expert_reviews', ['reviewer_id'], unique=False)
    op.create_table('fhir_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('profile_url', sa.Text(), nullable=False),
    sa.Column('resource_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sandbox_status', sa.String(length=50), nullable=False),
    sa.Column('sandbox_id', sa.String(length=255), nullable=True),
    sa.Column('sandbox_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('posted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fhir_observation', 'fhir_resources', ['observation_id'], unique=False)
    op.create_index('idx_fhir_sandbox_status', 'fhir_resources', ['sandbox_status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('observation_id', sa.UUID(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'read'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_fhir_sandbox_status', table_name='fhir_resources')
    op.drop_index('idx_fhir_observation', table_name='fhir_resources')
    op.drop_table('fhir_resources')
    op.drop_index('idx_reviews_reviewer', table_name='expert_reviews')
    op.drop_index('idx_reviews_observation', table_name='expert_reviews')
    op.drop_table('expert_reviews')
    op.drop_index('idx_ai_results_observation', table_name='ai_results')
    op.drop_index('idx_ai_results_obs_agent', table_name='ai_results')
    op.drop_index('idx_ai_results_agent', table_name='ai_results')
    op.drop_table('ai_results')
    op.drop_index('idx_observations_user_id', table_name='observations')
    op.drop_index('idx_observations_user_history', table_name='observations')
    op.drop_index('idx_observations_top_species', table_name='observations')
    op.drop_index('idx_observations_status_created', table_name='observations')
    op.drop_index('idx_observations_status', table_name='observations')
    op.drop_index('idx_observations_review_queue', table_name='observations')
    op.drop_index('idx_observations_pilot_city', table_name='observations')
    op.drop_index('idx_observations_created_at', table_name='observations')
    op.drop_index('idx_observations_confidence', table_name='observations')
    op.drop_table('observations')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_species_taxon', table_name='species_reference')
    op.drop_table('species_reference')
    # ### end Alembic commands ###
